Repository EyeSeeTea/glass-dev, pull requests merged in 2023-11, with the labels that each got.

#203 Feature - Check modules enrollment
  src/webapp/components/landing-content/LandingContent.tsx
  src/webapp/components/private-route/PrivateRoute.tsx
  src/webapp/hooks/useGlassModules.ts
  src/webapp/hooks/useGlassReadAccess.ts
  src/webapp/hooks/useOpenDataSubmissionsByOrgUnit.ts
Labels: small, waiting-for-review

#204 Hide current data submission for EGASP
  src/webapp/components/sidebar/mapModuleToMenu.ts
Labels: small, waiting-for-review

#207 Remove EGASP open submission card in landing page
  src/data/repositories/GlassDataSubmissionDefaultRepository.ts
Labels: small, waiting-for-review

#208 In uploads change records name to rows name and add values to tables
  i18n/en.pot
  i18n/es.po
  src/data/repositories/EGASPDataCSVDefaultRepository.ts
  src/data/repositories/RISDataCSVDefaultRepository.ts
  src/data/repositories/RISIndividualFunghiDataCSVDefaultRepository.ts
  src/data/repositories/SampleDataCSVDeafultRepository.ts
  src/domain/entities/GlassUploads.ts
  src/domain/repositories/data-entry/EGASPDataRepository.ts
  src/domain/repositories/data-entry/RISDataRepository.ts
  src/domain/repositories/data-entry/RISIndividualFunghiDataRepository.ts
  src/domain/repositories/data-entry/SampleDataRepository.ts
  src/domain/usecases/UploadDocumentUseCase.ts
  src/domain/usecases/data-entry/ValidatePrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidateSampleFileUseCase.tsx
  src/webapp/components/current-data-submission/UploadsTable.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/data-file-history/DataFileHistoryContent.tsx
  src/webapp/components/data-file-history/DataFileTable.tsx
  src/webapp/components/data-file-history/DataFileTableBody.tsx
  src/webapp/components/upload/UploadPrimaryFile.tsx
  src/webapp/components/upload/UploadSample.tsx
  src/webapp/entities/uploads.ts
Labels: medium, waiting-for-review

#210 Show import summary errors in uploads tables
  i18n/en.pot
  i18n/es.po
  src/CompositionRoot.ts
  src/data/repositories/GlassUploadsDefaultRepository.ts
  src/domain/entities/GlassUploads.ts
  src/domain/entities/data-entry/ImportSummary.ts
  src/domain/repositories/GlassUploadsRepository.ts
  src/domain/usecases/SaveImportSummaryErrorsOfFilesInUploadsUseCase.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/data-file-history/DataFileTable.tsx
  src/webapp/components/data-file-history/DataFileTableBody.tsx
  src/webapp/components/import-summary-errors-dialog/ImportSummaryErrorsDialog.tsx
  src/webapp/components/upload/BlockingErrors.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/UploadFiles.tsx
  src/webapp/entities/uploads.ts
Labels: large, waiting-for-review

#211 Add new rule higher than to questionnaire and show validation error message
  src/domain/entities/Questionnaire.ts
  src/webapp/components/questionnaire/QuestionInput.tsx
  src/webapp/components/questionnaire/widgets/NumberWidget.tsx
Labels: small, waiting-for-review

#209 AMC - Product File upload and deletion
  i18n/en.pot
  i18n/es.po
  src/CompositionRoot.ts
  src/data/repositories/ExcelPopulateDefaultRepository.ts
  src/data/repositories/InstanceDefaultRepository.ts
  src/data/repositories/TrackerDefaultRepository.ts
  src/data/repositories/data-entry/AMCProductDataRepository.ts
  src/data/repositories/data-entry/AMCSubstanceDataRepository.ts
  src/data/repositories/data-entry/DataValuesDefaultRepository.ts
  src/data/repositories/data-entry/EGASPDataCSVDefaultRepository.ts
  src/data/repositories/data-entry/RISDataCSVDefaultRepository.ts
  src/data/repositories/data-entry/RISIndividualFunghiDataCSVDefaultRepository.ts
  src/data/repositories/data-entry/SampleDataCSVDeafultRepository.ts
  src/data/repositories/download-empty-template/EGASPDownloadEmptyTemplate.ts
  src/data/repositories/download-empty-template/EGASPProgramDefaultRepository.ts
  src/data/repositories/download-empty-template/sheetBuilder.ts
  src/domain/entities/DataForm.ts
  src/domain/entities/Geometry.ts
  src/domain/entities/GlassModule.ts
  src/domain/entities/Relationship.ts
  src/domain/entities/Template.ts
  src/domain/entities/TrackedEntityInstance.ts
  src/domain/entities/data-entry/DataPackage.ts
  src/domain/entities/data-entry/egasp-templates/index.ts
  src/domain/entities/data-entry/program-templates/ProgramGenerated.04.ts
  src/domain/entities/data-entry/program-templates/TrackerProgramGenerated.03.ts
  src/domain/entities/data-entry/program-templates/index.ts
  src/domain/repositories/ExcelRepository.ts
  src/domain/repositories/TrackerRepository.ts
  src/domain/repositories/data-entry/AMCDataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidatePrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidateSampleFileUseCase.tsx
  src/domain/usecases/data-entry/amc/ImportAMCProductLevelData.ts
  src/domain/usecases/data-entry/amc/ImportAMCQuestionnaireData.ts
  src/domain/usecases/data-entry/amr-individual-funghi/ImportRISIndividualFunghiFile.ts
  src/domain/usecases/data-entry/egasp/GetEGASPEmptyTemplateUseCase.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
  src/domain/utils/ExcelReader.ts
  src/domain/utils/ModuleProperties.ts
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/components/upload/UploadFiles.tsx
  src/webapp/components/upload/UploadSample.tsx
Labels: large, waiting-for-review
