Repository EyeSeeTea/glass-dev, pull requests merged in 2023-10, with the labels that each got.

#190 custom validations should consider clinic as ou + add lab_id column to egasp template
  src/data/repositories/Dhis2EventsDefaultRepository.ts
  src/data/repositories/download-empty-template/sheetBuilder.ts
  src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
Labels: small, waiting-for-review

#191 Feature - Redirect to homepage if on EAR and has no permission
  src/webapp/components/layouts/main-layout/MainLayout.tsx
  src/webapp/components/private-route/PrivateRoute.tsx
  src/webapp/components/sidebar/SideBar.tsx
  src/webapp/context-providers/SideBarModulesContextProvider.tsx
  src/webapp/context-providers/SideBarProvider.tsx
  src/webapp/contexts/sidebar-modules-context.ts
  src/webapp/pages/Router.tsx
Labels: large, waiting-for-review

#193 fix: revert incorrect access logic
  i18n/en.pot
  i18n/es.po
  src/webapp/components/private-route/PrivateRoute.tsx
Labels: small, waiting-for-review

#172 fix: handle submit help ticket click
  src/webapp/components/upload/SupportButtons.tsx
Labels: small, waiting-for-review

#189 Feat/error msg improvments
  src/data/repositories/ExcelPopulateDefaultRepository.ts
  src/data/repositories/MetadataDefaultRepository.ts
  src/domain/repositories/MetadataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
  src/domain/usecases/data-entry/utils/getCategoryOptionCombo.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/UploadFiles.tsx
Labels: medium, waiting-for-review

#196 Org Unit Selector Fix
  src/webapp/components/app-bar/OrgUnitSelector.tsx
  src/webapp/components/app-bar/SearchInput.tsx
  src/webapp/components/module-card/ModuleCard.tsx
  src/webapp/context-providers/CurrentOrgUnitContextProvider.tsx
Labels: medium, waiting-for-review

#197 EGASP - async import
  src/data/repositories/Dhis2EventsDefaultRepository.ts
  src/data/repositories/TrackerDefaultRepository.ts
  src/data/repositories/utils/TrackerPostResponseDefaultError.ts
Labels: medium, waiting-for-review

#198 Misc bug fixes - EGASP
  src/data/repositories/InstanceDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/entities/User.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
  src/domain/utils/ModuleProperties.ts
  src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
  src/webapp/components/data-file-history/Filter.tsx
  src/webapp/components/data-submissions-history/hooks/usePopulateDataSubmissionHistory.ts
  src/webapp/contexts/current-module-context.ts
  src/webapp/hooks/useGlassDataSubmissionsByModuleAndOU.ts
Labels: small, waiting-for-review

#201 AMR-Individual - Add required attributes to tracked entity
  src/data/repositories/RISDataCSVDefaultRepository.ts
  src/data/repositories/RISIndividualDataCSVDefaultRepository.ts
  src/data/repositories/SampleDataCSVDeafultRepository.ts
  src/data/repositories/SpreadsheetXlsxDefaultRepository.ts
  src/data/repositories/utils/CSVUtils.ts
  src/domain/repositories/SpreadsheetXlsxRepository.ts
  src/domain/usecases/data-entry/amr-i/ImportRISIndividualFile.ts
Labels: medium, waiting-for-review

#202 AMR-Funghi import
  src/CompositionRoot.ts
  src/data/repositories/RISIndividualFunghiDataCSVDefaultRepository.ts
  src/domain/entities/data-entry/amr-individual-funghi-external/RISIndividualFunghiData.ts
  src/domain/repositories/data-entry/RISIndividualDataRepository.ts
  src/domain/repositories/data-entry/RISIndividualFunghiDataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidatePrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/amr-individual-funghi/ImportRISIndividualFunghiFile.ts
  src/domain/utils/ModuleProperties.ts
Labels: medium, waiting-for-review
