Repository EyeSeeTea/glass-dev, pull requests merged in 2023-04, with the labels that each got.

#88 dry run imports and import only if no blocking errors
  i18n/en.pot
  i18n/es.po
  src/data/repositories/DataValuesDefaultRepository.ts
  src/domain/repositories/data-entry/DataValuesRepository.ts
  src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
  src/domain/usecases/data-entry/ImportSampleFileUseCase.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/components/upload/UploadContent.tsx
Labels: large, waiting-for-review

#95 Add lines information of block errors validations
  i18n/en.pot
  i18n/es.po
  src/domain/entities/data-entry/ImportSummary.ts
  src/domain/usecases/data-entry/utils/checkASTResults.ts
  src/domain/usecases/data-entry/utils/checkBatchId.ts
  src/domain/usecases/data-entry/utils/checkCountry.ts
  src/domain/usecases/data-entry/utils/checkPathogenAntibiotic.ts
  src/domain/usecases/data-entry/utils/checkSpecimenPathogen.ts
  src/domain/usecases/data-entry/utils/checkYear.ts
  src/webapp/components/upload/BlockingErrors.tsx
Labels: medium, waiting-for-review

#97 Add uploaded files & questionnaires info on modules card
  src/webapp/components/module-card/ModuleCard.tsx
Labels: small, waiting-for-review

#98 Hide validations tab and reports menu until functionality is complete
  src/webapp/components/current-data-submission/UploadSteps.tsx
  src/webapp/components/sidebar/mapModuleToMenu.ts
Labels: small, waiting-for-review

#99 Delete files with appropriate info message
  i18n/en.pot
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
Labels: medium, waiting-for-review

#100 upload history table on click behavior
  i18n/en.pot
  i18n/es.po
  src/webapp/components/upload-history/UploadTable.tsx
  src/webapp/components/upload-history/UploadTableBody.tsx
Labels: small, waiting-for-review

#103 fix: remove all countries with region NA
  src/data/repositories/InstanceDefaultRepository.ts
Labels: small, waiting-for-review

#105 fix: dataset page ux enhancement
  i18n/en.pot
  i18n/es.po
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
Labels: small, waiting-for-review

#106 Feat/consistency check zeroes
  i18n/en.pot
  i18n/es.po
  src/domain/usecases/data-entry/utils/checkASTResults.ts
Labels: small, waiting-for-review

#107 Refine upload workflow to handle dry run, different statuses and deletion
  i18n/en.pot
  i18n/es.po
  src/CompositionRoot.ts
  src/data/repositories/GlassUploadsDefaultRepository.ts
  src/domain/entities/GlassUploads.ts
  src/domain/repositories/GlassUploadsRepository.ts
  src/domain/usecases/SetUploadStatusUseCase.tsx
  src/domain/usecases/UpdateSampleUploadWithRisIdUseCase.ts
  src/domain/usecases/UploadDocumentUseCase.ts
  src/domain/usecases/ValidateGlassUploadsUseCase.ts
  src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/components/upload/UploadContent.tsx
  src/webapp/components/upload/UploadFiles.tsx
  src/webapp/entities/uploads.ts
Labels: large, waiting-for-review

#104 fix: data submission ux enhancement
  i18n/en.pot
  i18n/es.po
  src/webapp/pages/current-data-submission/CurrentDataSubmissionPage.tsx
Labels: small, waiting-for-review

#108 Embed Reports in Iframe
  i18n/en.pot
  i18n/es.po
  src/webapp/components/reports/EmbeddedReport.tsx
  src/webapp/components/sidebar/mapModuleToMenu.ts
  src/webapp/pages/Router.tsx
  src/webapp/pages/reports/ReportsPage.tsx
Labels: medium, waiting-for-review

#109 Fetch Dashboard id from datastore
  src/CompositionRoot.ts
  src/domain/entities/GlassModule.ts
  src/domain/usecases/GetReportDashboardUseCase.ts
  src/domain/usecases/ValidateGlassModulesUseCase.ts
  src/webapp/hooks/useGlassReportDashboard.ts
  src/webapp/pages/reports/ReportsPage.tsx
Labels: small, waiting-for-review

#110 Sortable columns in Upload history
  i18n/en.pot
  i18n/es.po
  src/data/repositories/RISDataCSVRepository.ts
  src/domain/repositories/data-entry/RISDataRepository.ts
  src/domain/usecases/UploadDocumentUseCase.ts
  src/domain/usecases/data-entry/ValidateRISFileUseCase.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload-history/UploadHistoryContent.tsx
  src/webapp/components/upload-history/UploadTable.tsx
  src/webapp/components/upload-history/UploadTableBody.tsx
  src/webapp/components/upload-history/mock-tables-data.json
  src/webapp/components/upload/UploadRis.tsx
  src/webapp/components/upload/UploadSample.tsx
Labels: large, waiting-for-review

#112 Populate upload status dropdown
  i18n/en.pot
  src/domain/usecases/SetUploadStatusUseCase.tsx
  src/webapp/components/upload-history/Filter.tsx
Labels: medium, waiting-for-review

#115 Add sharing settings to uploaded docs
  src/CompositionRoot.ts
  src/data/repositories/GlassDocumentsDefaultRepository.ts
  src/domain/repositories/GlassDocumentsRepository.ts
  src/domain/usecases/UploadDocumentUseCase.ts
  src/domain/usecases/ValidateGlassDocumentsUseCase.ts
  src/webapp/components/upload/UploadRis.tsx
  src/webapp/components/upload/UploadSample.tsx
Labels: medium, waiting-for-review

#117 Add notifications information on header
  src/webapp/components/app-bar/GlassAppBar.tsx
Labels: small, waiting-for-review

#118 Fix responsiveness with table
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
  src/webapp/components/current-data-submission/UploadsTable.tsx
Labels: small, waiting-for-review

#119 [questionnaires] Toggle sections visibility from data element value
  .nvmrc
  src/data/dhis2/DataElement.ts
  src/data/dhis2/DataElementD2Source.ts
  src/data/dhis2/DataForm.ts
  src/data/dhis2/DataFormD2Source.ts
  src/data/repositories/QuestionnaireD2Repository.ts
  src/domain/entities/Base.ts
  src/domain/entities/GlassModule.ts
  src/domain/entities/Questionnaire.ts
  src/webapp/components/questionnaire/QuestionnaireForm.tsx
  src/webapp/components/upload/Completed.tsx
Labels: small, waiting-for-review

#113 Toggle Menu and set max width
  i18n/en.pot
  i18n/es.po
  src/webapp/components/app-bar/GlassAppBar.tsx
  src/webapp/components/custom-card/CustomCard.tsx
  src/webapp/components/layouts/main-layout/MainLayout.tsx
  src/webapp/components/sidebar/SideBar.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/pages/app/App.css
Labels: large, waiting-for-review

#120 Validate data set before setting questionnaire as completed
  i18n/en.pot
  i18n/es.po
  src/data/repositories/QuestionnaireD2Repository.ts
  src/webapp/components/questionnaire/QuestionnaireForm.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
Labels: medium, waiting-for-review

#121 Change upload history to data file history
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/components/data-file-history/DataFileHistoryContent.tsx
  src/webapp/components/data-file-history/DataFileTable.tsx
  src/webapp/components/data-file-history/DataFileTableBody.tsx
  src/webapp/components/data-file-history/Filter.tsx
  src/webapp/components/sidebar-nav/SidebarNavMenu.tsx
  src/webapp/components/sidebar/mapModuleToMenu.ts
  src/webapp/pages/Router.tsx
  src/webapp/pages/data-file-history/DataFileHistoryPage.tsx
Labels: small, waiting-for-review

#122 feat: send notification on status change
  i18n/en.pot
  src/CompositionRoot.ts
  src/data/repositories/NotificationDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/repositories/NotificationRepository.ts
  src/domain/usecases/SendNotificationsUseCase.ts
  src/domain/usecases/ValidateGlassModulesUseCase.ts
  src/webapp/components/current-data-submission/AdvancedButtons.tsx
  src/webapp/components/current-data-submission/Questionnaires.tsx
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
  src/webapp/hooks/useCurrentUserGroupsAccess.ts
Labels: medium, waiting-for-review

#123 Add who logo link to dhis2 homepage
  src/webapp/components/app-bar/GlassAppBar.tsx
Labels: small, waiting-for-review

#124 Unhide validations tab and embed there the unapproved data dashboard
  i18n/en.pot
  src/CompositionRoot.ts
  src/data/repositories/SystemSettingsDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/repositories/SystemSettingsRepository.ts
  src/domain/usecases/GetDashboardUseCase.ts
  src/domain/usecases/GetLastAnalyticsRunTimeUseCase.ts
  src/domain/usecases/ValidateGlassModulesUseCase.ts
  src/webapp/components/current-data-submission/UploadSteps.tsx
  src/webapp/components/current-data-submission/Validations.tsx
  src/webapp/hooks/useGetLastSuccessfulAnalyticsRunTime.ts
  src/webapp/hooks/useGlassDashboard.ts
  src/webapp/hooks/useGlassReportDashboard.ts
  src/webapp/pages/reports/ReportsPage.tsx
Labels: large, waiting-for-review

#125 fix: send notification only to users in specific userGroups and Org Units
  src/CompositionRoot.ts
  src/data/repositories/NotificationDefaultRepository.ts
  src/data/repositories/UsersDefaultRepository.ts
  src/domain/repositories/NotificationRepository.ts
  src/domain/repositories/UsersRepository.ts
  src/domain/usecases/SendNotificationsUseCase.ts
  src/webapp/components/current-data-submission/AdvancedButtons.tsx
  src/webapp/components/current-data-submission/Questionnaires.tsx
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
Labels: small, waiting-for-review

#126 fix: show continuous analytics run time, if present
  src/CompositionRoot.ts
  src/data/repositories/SystemInfoDefaultRepository.ts
  src/data/repositories/SystemSettingsDefaultRepository.ts
  src/domain/repositories/SystemInfoRepository.ts
  src/domain/repositories/SystemSettingsRepository.ts
  src/domain/usecases/GetLastAnalyticsRunTimeUseCase.ts
  src/webapp/components/current-data-submission/Validations.tsx
  src/webapp/hooks/useGetLastSuccessfulAnalyticsRunTime.ts
Labels: small, waiting-for-review

#127 fix: hide edit elements in embedded reports
  src/webapp/components/reports/EmbeddedReport.tsx
Labels: small, waiting-for-review

#128 User Profile
  i18n/en.pot
  i18n/es.po
  src/CompositionRoot.ts
  src/data/repositories/InstanceDefaultRepository.ts
  src/data/repositories/LocalesDefaultRepository.ts
  src/domain/entities/User.ts
  src/domain/repositories/LocalesRepository.ts
  src/domain/usecases/GetDatabaseLocalesUseCase.ts
  src/domain/usecases/GetUiLocalesUseCase.ts
  src/utils/tests.tsx
  src/webapp/components/app-bar/GlassAppBar.tsx
  src/webapp/components/user-profile/UserProfileContent.tsx
  src/webapp/components/user-profile/UserSettingsContent.tsx
  src/webapp/pages/Router.tsx
  src/webapp/pages/user-profile/UserProfilePage.tsx
  src/webapp/pages/user-profile/UserSettings.tsx
Labels: large, waiting-for-review

#135 fix: update status and button colors
  i18n/en.pot
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
  src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
  src/webapp/components/current-data-submission/overview/StatusDetails.ts
  src/webapp/pages/app/themes/dhis2.theme.ts
Labels: medium, waiting-for-review

#136 fix: enable add filter button for embedded reports
  i18n/en.pot
  i18n/es.po
  src/webapp/components/reports/EmbeddedReport.tsx
Labels: medium, waiting-for-review

#137 fix: who logo click handling
  src/webapp/components/app-bar/GlassAppBar.tsx
Labels: small, waiting-for-review
