Repository EyeSeeTea/glass-dev, pull requests merged in 2023-09, with the labels that each got.

#173 EAR implementation
  .gitignore
  i18n/en.pot
  i18n/es.po
  package.json
  src/CompositionRoot.ts
  src/data/data-store/DataStoreKeys.ts
  src/data/repositories/CaptureFormDefaultRepository.ts
  src/data/repositories/Dhis2EventsDefaultRepository.ts
  src/data/repositories/InstanceDefaultRepository.ts
  src/data/repositories/QuestionnaireD2DefaultRepository.ts
  src/data/repositories/SignalDefaultRepository.ts
  src/data/repositories/UsersDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/entities/Questionnaire.ts
  src/domain/entities/Signal.ts
  src/domain/entities/User.ts
  src/domain/repositories/CaptureFormRepository.ts
  src/domain/repositories/SignalRepository.ts
  src/domain/repositories/UsersRepository.ts
  src/domain/usecases/DeleteSignalUseCase.tsx
  src/domain/usecases/GetCaptureFormQuestionsUseCase.tsx
  src/domain/usecases/GetSignalEventUseCase.tsx
  src/domain/usecases/GetSignalsUseCase.ts
  src/domain/usecases/GetSpecificDataSubmissionUseCase.ts
  src/domain/usecases/SendNotificationsUseCase.ts
  src/domain/usecases/ValidateGlassModulesUseCase.ts
  src/domain/usecases/data-entry/ear/ImportCaptureDataUseCase.tsx
  src/webapp/components/current-data-submission/AdvancedButtons.tsx
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
  src/webapp/components/current-data-submission/Questionnaires.tsx
  src/webapp/components/current-data-submission/Submission.tsx
  src/webapp/components/data-file-history/DataFileTable.tsx
  src/webapp/components/data-file-history/DataFileTableBody.tsx
  src/webapp/components/landing-content/notifications/NotificationDialog.tsx
  src/webapp/components/new-signal/NewSignalForm.tsx
  src/webapp/components/new-signal/hook/useNewSignalForm.ts
  src/webapp/components/questionnaire/QuestionInput.tsx
  src/webapp/components/questionnaire/QuestionRow.tsx
  src/webapp/components/questionnaire/QuestionnaireForm.tsx
  src/webapp/components/questionnaire/widgets/DatePickerWidget.tsx
  src/webapp/components/questionnaire/widgets/SingleSelectWidget.tsx
  src/webapp/components/sidebar/mapModuleToMenu.ts
  src/webapp/components/signals/SignalTableContent.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/contexts/current-orgUnit-context.ts
  src/webapp/hooks/useCurrentUserGroupsAccess.ts
  src/webapp/hooks/useSignals.ts
  src/webapp/pages/Router.tsx
  src/webapp/pages/new-signal/NewSignalPage.tsx
  src/webapp/pages/new-signal/SignalPage.tsx
  src/webapp/pages/signals/SignalsPage.tsx
Labels: large, waiting-for-review

#179 Check in EGASP upload document that clinic is inside clinics in the selected country
  src/data/repositories/MetadataDefaultRepository.ts
  src/domain/repositories/MetadataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
Labels: medium, waiting-for-review

#176 Feature/change api endpoints
  package.json
  src/data/repositories/CaptureFormDefaultRepository.ts
  src/data/repositories/CountryInformationDefaultRepository.ts
  src/data/repositories/Dhis2EventsDefaultRepository.ts
  src/domain/entities/CountryInformation.ts
  src/domain/entities/program-rules/EventEffectTypes.ts
  src/domain/repositories/CaptureFormRepository.ts
  src/domain/usecases/DeleteSignalUseCase.tsx
  src/domain/usecases/data-entry/amr-i/ImportRISIndividualFile.ts
  src/domain/usecases/data-entry/ear/ImportCaptureDataUseCase.tsx
  src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
  src/domain/usecases/program-rules-processing/ProgramRuleValidationForEGASP.ts
  yarn.lock
Labels: large, waiting-for-review

#182 Show orgUnit shortName & add search functionality
  i18n/en.pot
  i18n/es.po
  src/data/repositories/InstanceDefaultRepository.ts
  src/domain/entities/User.ts
  src/webapp/components/app-bar/GlassAppBar.tsx
  src/webapp/components/app-bar/OrgUnitSelector.tsx
  src/webapp/components/app-bar/SearchInput.tsx
  src/webapp/contexts/current-orgUnit-context.ts
Labels: large, waiting-for-review

#185 Download Empty Template implementation for EGASP
  i18n/en.pot
  i18n/es.po
  package.json
  src/CompositionRoot.ts
  src/data/data-store/BulkLoadDataStoreClient.ts
  src/data/repositories/ExcelPopulateDefaultRepository.ts
  src/data/repositories/MetadataDefaultRepository.ts
  src/data/repositories/download-empty-template/EGASPDownloadEmptyTemplate.ts
  src/data/repositories/download-empty-template/EGASPProgramDefaultRepository.ts
  src/data/repositories/download-empty-template/sheetBuilder.ts
  src/data/repositories/download-empty-template/utils/colors.ts
  src/domain/entities/DataForm.ts
  src/domain/entities/Palette.ts
  src/domain/repositories/DownloadEmptyTemplateRepository.ts
  src/domain/repositories/ExcelRepository.ts
  src/domain/repositories/MetadataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
  src/domain/usecases/data-entry/egasp/GetEGASPEmptyTemplateUseCase.ts
  src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
  src/domain/utils/ModuleProperties.ts
  src/webapp/components/upload/UploadFiles.tsx
  yarn.lock
Labels: large, waiting-for-review

#187 fix: module card should always be aligned to the left
  src/webapp/components/landing-content/OpenDataSubmissions.tsx
Labels: small, waiting-for-review
