Repository EyeSeeTea/glass-dev, pull requests merged in 2023-05, with the labels that each got.

#132 feat: fix upload steps buttons layout, disable on blocking error
  i18n/en.pot
  i18n/es.po
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/components/upload/SupportButtons.tsx
  src/webapp/components/upload/UploadContent.tsx
  src/webapp/components/upload/UploadFiles.tsx
Labels: medium, waiting-for-review

#131 feat: add notification message text to card
  src/webapp/components/current-data-submission/AdvancedButtons.tsx
  src/webapp/components/current-data-submission/Questionnaires.tsx
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
Labels: small, waiting-for-review

#140 feat: show action required on module cards
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
  src/webapp/components/current-data-submission/overview/StatusDetails.ts
  src/webapp/components/module-card/ModuleCard.tsx
Labels: small, waiting-for-review

#141 fix: change sentence
  src/webapp/components/current-data-submission/Advanced.tsx
Labels: small, waiting-for-review

#142 fix: typo corrections
  i18n/en.pot
  i18n/es.po
  src/webapp/components/current-data-submission/Questionnaires.tsx
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/utils/editModeStatus.ts
Labels: small, waiting-for-review

#143 feat: add link to landing page on glass logo
  src/webapp/components/app-bar/GlassAppBar.tsx
Labels: small, waiting-for-review

#144 fix: error treatment
  i18n/en.pot
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/data-submissions-history/DataSubmissionsHistoryContent.tsx
  src/webapp/components/data-submissions-history/DataSubmissionsTable.tsx
  src/webapp/components/upload/UploadSample.tsx
  src/webapp/hooks/useGlassDataSubmissionsByModuleAndOU.ts
Labels: small, waiting-for-review

#147 fix: add fix to selects to not add padding on body, on open
  src/webapp/components/app-bar/GlassAppBar.tsx
  src/webapp/components/data-file-history/Filter.tsx
  src/webapp/components/upload/UploadFiles.tsx
  src/webapp/components/user-profile/UserSettingsContent.tsx
Labels: small, waiting-for-review

#150 fix: NUMINFECTED column not mandatory
  src/data/repositories/SampleDataCSVRepository.ts
Labels: small, waiting-for-review

#151 fix: history till 2016
  src/webapp/components/data-file-history/Filter.tsx
  src/webapp/components/data-submissions-history/DataSubmissionsHistoryContent.tsx
Labels: small, waiting-for-review

#152 Fix/tab reorder
  i18n/en.pot
  i18n/es.po
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/components/current-data-submission/Submission.tsx
  src/webapp/components/current-data-submission/UploadSteps.tsx
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
  src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
  src/webapp/components/current-data-submission/overview/Overview.tsx
  src/webapp/components/current-data-submission/overview/StatusDetails.ts
Labels: large, waiting-for-review

#153 feat: allow change ui & database languages
  i18n/en.pot
  i18n/es.po
  src/CompositionRoot.ts
  src/data/repositories/UsersDefaultRepository.ts
  src/domain/repositories/UsersRepository.ts
  src/domain/usecases/SaveKeyDbLocaleUseCase.ts
  src/domain/usecases/SaveKeyUiLocaleUseCase.ts
  src/domain/usecases/SavePasswordUseCase.ts
  src/webapp/components/user-profile/UserProfileContent.tsx
  src/webapp/components/user-profile/UserSettingsContent.tsx
Labels: medium, waiting-for-review

#134 Empty datasets and empty open data submission handling.
  i18n/en.pot
  i18n/es.po
  src/webapp/components/current-data-submission/ListOfDatasets.tsx
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/landing-content/LandingContent.tsx
  src/webapp/components/landing-content/OpenDataSubmissions.tsx
  src/webapp/components/landing-content/notifications/YourNotifications.tsx
Labels: medium, waiting-for-review

#154 fix: show validation report when ready on summary page
  src/data/repositories/DataValuesDefaultRepository.ts
  src/data/repositories/SystemInfoDefaultRepository.ts
  src/domain/entities/data-entry/DataValuesSaveSummary.ts
  src/domain/entities/data-entry/ImportSummary.ts
  src/domain/repositories/SystemInfoRepository.ts
  src/domain/usecases/GetLastAnalyticsRunTimeUseCase.ts
  src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
  src/webapp/components/current-data-submission/Validations.tsx
  src/webapp/components/reports/EmbeddedReport.tsx
  src/webapp/components/upload/ReviewDataSummary.tsx
  src/webapp/hooks/useGetLastSuccessfulAnalyticsRunTime.ts
Labels: medium, waiting-for-review

#156 fix: buttons padding and bgcolor. Action req text
  i18n/en.pot
  src/webapp/components/current-data-submission/StatusMap.ts
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/current-data-submission/overview/CtaButtons.tsx
  src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
Labels: medium, waiting-for-review

#160 delete confirmation text and some improvements.
  i18n/en.pot
  src/domain/usecases/DownloadDocumentUseCase.ts
  src/domain/usecases/data-entry/ImportEGASPFile.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/utils/ModuleProperties.ts
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
Labels: medium, waiting-for-review
