Repository EyeSeeTea/glass-dev, pull requests merged in 2024-01, with the labels that each got.

#221 Add all filter in data file history page
  src/webapp/components/data-file-history/DataFileHistoryContent.tsx
  src/webapp/components/data-file-history/Filter.tsx
Labels: small, waiting-for-review

#222 Calculation consumption substance level data
  src/CompositionRoot.ts
  src/data/repositories/GlassATCDefaultRepository.ts
  src/data/repositories/GlassUploadsDefaultRepository.ts
  src/data/repositories/data-entry/AMCProductDataDefaultRepository.ts
  src/data/repositories/data-entry/AMCSubstanceDataDefaultRepository.ts
  src/data/repositories/data-entry/AMCSubstanceDataRepository.ts
  src/domain/entities/GlassATC.ts
  src/domain/entities/GlassUploads.ts
  src/domain/entities/data-entry/amc/CalculatedConsumptionDataProgram.ts
  src/domain/entities/data-entry/amc/RawSubstanceConsumptionCalculated.ts
  src/domain/entities/data-entry/amc/RawSubstanceConsumptionData.ts
  src/domain/entities/data-entry/amc/SubstanceConsumptionCalculated.ts
  src/domain/repositories/GlassATCRepository.ts
  src/domain/repositories/GlassUploadsRepository.ts
  src/domain/repositories/data-entry/AMCSubstanceDataRepository.ts
  src/domain/usecases/DeleteDocumentInfoByUploadIdUseCase.tsx
  src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
  src/domain/usecases/data-entry/ImportSecondaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidateSampleFileUseCase.tsx
  src/domain/usecases/data-entry/amc/CalculateConsumptionDataProductLevelUseCase.ts
  src/domain/usecases/data-entry/amc/CalculateConsumptionDataSubstanceLevelUseCase.ts
  src/domain/usecases/data-entry/amc/ImportAMCSubstanceLevelData.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionProductLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionSubstanceLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/data/atcVersionsByKeys.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/calculationConsumptionSubstanceLevelBasic.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/calculationSolutionNoCombCodeNoFoundDDD.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataAtcNotFound.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataBasic.json
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionProductLevelData.ts
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionSubstanceLevelData.ts
  src/webapp/components/current-data-submission/UploadsTableBody.tsx
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/entities/uploads.ts
Labels: large, waiting-for-review

#224 fix: set import event status as completed
  src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
  src/domain/usecases/data-entry/amc/ImportAMCProductLevelData.ts
  src/domain/usecases/data-entry/amr-individual-funghi/ImportRISIndividualFunghiFile.ts
Labels: small, waiting-for-review

#227 Fix AMC calculations when atc data not found
  src/data/repositories/GlassATCDefaultRepository.ts
  src/domain/entities/GlassATC.ts
  src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionProductLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionSubstanceLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/data/atcCurrentVersionData.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/atcVersionsByKeys.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/calculationConsumptionSubstanceLevelBasic.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataAtcNotFound.json
  src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataBasic.json
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionProductLevelData.ts
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionSubstanceLevelData.ts
Labels: large, waiting-for-review

#231 feat: wording changes from funghi to fungal
  src/CompositionRoot.ts
  src/data/repositories/data-entry/RISIndividualFungalDataCSVDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/entities/data-entry/amr-individual-fungal-external/RISIndividualFungalData.ts
  src/domain/repositories/data-entry/RISIndividualFungalDataRepository.ts
  src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/ValidatePrimaryFileUseCase.tsx
  src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
  src/domain/utils/ModuleProperties.ts
Labels: small, waiting-for-review

#232 Multiple dashboards support for AMC Report Menu and Validation Report
  src/CompositionRoot.ts
  src/domain/entities/GlassModule.ts
  src/domain/usecases/GetMultipleDashboardUseCase.ts
  src/domain/utils/ModuleProperties.ts
  src/webapp/components/current-data-submission/Validations.tsx
  src/webapp/components/reports/MultiDashboardContent.tsx
  src/webapp/hooks/useGlassDashboard.ts
  src/webapp/hooks/useGlassMultiDashboard.ts
  src/webapp/pages/reports/ReportsPage.tsx
Labels: medium, waiting-for-review
