Repository EyeSeeTea/glass-dev, pull requests merged in 2024-02, with the labels that each got.

#235 Download all data for modules with Individual data
  src/CompositionRoot.ts
  src/data/repositories/EventVisualizationAnalyticsDefaultRepository.ts
  src/domain/entities/GlassModule.ts
  src/domain/repositories/EventVisualizationAnalyticsRepository.ts
  src/domain/usecases/DownloadAllDataButtonData.ts
  src/domain/usecases/DownloadAllDataForModuleUseCase.ts
  src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
  src/domain/utils/ModuleProperties.ts
  src/webapp/hooks/useDownloadAllData.ts
  src/webapp/pages/reports/ReportsPage.tsx
Labels: medium, waiting-for-review

#234 fix: replace icon from generic to glass icon
  icon.png
Labels: small, waiting-for-review

#229 Script AMC recalculations
  README.md
  package.json
  src/data/data-store/DataStoreKeys.ts
  src/data/repositories/GlassATCDefaultRepository.ts
  src/data/repositories/data-entry/AMCProductDataDefaultRepository.ts
  src/data/repositories/data-entry/AMCSubstanceDataDefaultRepository.ts
  src/domain/entities/Future.ts
  src/domain/entities/GlassATC.ts
  src/domain/entities/data-entry/amc/ProductDataTrackedEntity.ts
  src/domain/entities/data-entry/amc/RawSubstanceConsumptionCalculated.ts
  src/domain/entities/data-entry/amc/Salt.ts
  src/domain/entities/data-entry/amc/SubstanceConsumptionCalculated.ts
  src/domain/repositories/GlassATCRepository.ts
  src/domain/repositories/data-entry/AMCProductDataRepository.ts
  src/domain/repositories/data-entry/AMCSubstanceDataRepository.ts
  src/domain/usecases/data-entry/amc/CalculateConsumptionDataProductLevelUseCase.ts
  src/domain/usecases/data-entry/amc/CalculateConsumptionDataSubstanceLevelUseCase.ts
  src/domain/usecases/data-entry/amc/DisableAMCRecalculationsUseCase.ts
  src/domain/usecases/data-entry/amc/GetCurrentATCVersionData.ts
  src/domain/usecases/data-entry/amc/GetRecalculateDataInfoUseCase.ts
  src/domain/usecases/data-entry/amc/RecalculateConsumptionDataProductLevelForAllUseCase.ts
  src/domain/usecases/data-entry/amc/RecalculateConsumptionDataSubstanceLevelForAllUseCase.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionProductLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/calculationConsumptionSubstanceLevelData.spec.ts
  src/domain/usecases/data-entry/amc/utils/__tests__/data/atcVersionsByKeys.json
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionProductLevelData.ts
  src/domain/usecases/data-entry/amc/utils/calculationConsumptionSubstanceLevelData.ts
  src/domain/usecases/data-entry/amc/utils/getConsumptionDataProductLevel.ts
  src/domain/usecases/data-entry/amc/utils/getConsumptionDataSubstanceLevel.ts
  src/scripts/cli.ts
  src/scripts/cliAMC.ts
  src/scripts/commands/example.ts
  src/scripts/common.ts
  src/scripts/example.ts
  src/scripts/index.ts
  src/scripts/tsconfig.json
  src/utils/log.ts
  src/utils/logger.ts
  src/utils/ts-utils.ts
  src/webapp/components/upload/ConsistencyChecks.tsx
  src/webapp/context-providers/CurrentOrgUnitContextProvider.tsx
  src/webapp/contexts/app-context.ts
  src/webapp/pages/app/App.tsx
  yarn.lock
Labels: large, waiting-for-review
